import * as Localization from 'expo-localization';

export const translations = {
  en: {
    // App & Auth
    appName: 'BetterU',
    tagline: 'Your fitness journey starts here',
    enterPassword: 'Enter Password',
    login: 'Login',
    loggingIn: 'Logging in...',
    passwordRequired: 'Password Required',
    pleaseEnterPassword: 'Please enter your password',
    incorrectPassword: 'Incorrect Password',
    incorrectPasswordMessage: 'The password you entered is incorrect. Please try again.',
    error: 'Error',
    authError: 'Failed to save authentication state',
    
    // Tab Navigation
    calories: 'Calories',
    workouts: 'Workouts',
    plans: 'Plans',
    profile: 'Profile',
    
    // Plans Screen
    trainingPlans: 'Training Plans',
    findPerfectProgram: 'Find your perfect workout program',
    browsePlans: 'Browse Plans',
    myPlans: 'My Plans',
    searchPlans: 'Search plans...',
    category: 'Category',
    duration: 'Duration',
    difficulty: 'Difficulty',
    all: 'All',
    strength: 'Strength',
    cardio: 'Cardio',
    flexibility: 'Flexibility',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    anyDuration: 'Any Duration',
    oneToFourWeeks: '1-4 weeks',
    fiveToEightWeeks: '5-8 weeks',
    ninePlusWeeks: '9+ weeks',
    allLevels: 'All Levels',
    weeks: 'weeks',
    workoutsCount: 'workouts',
    viewPlan: 'View Plan',
    purchase: 'Purchase',
    purchaseRequired: 'Purchase Required',
    thisPlanCosts: 'This plan costs',
    wouldYouLikeToPurchase: 'Would you like to purchase it?',
    cancel: 'Cancel',
    viewPlanDetails: 'View plan details and workouts.',
    close: 'Close',
    downloadPDF: 'Download PDF',
    downloadPDFMessage: 'PDF download will be available soon!',
    paymentIntegration: 'Payment integration will be added soon!',
    noPlansMatch: 'No plans match your filters',
    noPurchasedPlans: "You haven't purchased any plans yet",
    
    // Workouts Screen
    myWorkouts: 'My Workouts',
    trackYourProgress: 'Track your progress and exercises',
    todaysWorkout: "Today's Workout",
    recentWorkouts: 'Recent Workouts',
    exerciseLibrary: 'Exercise Library',
    startWorkout: 'Start Workout',
    logWorkout: 'Log Workout',
    searchExercises: 'Search exercises...',
    sets: 'sets',
    reps: 'reps',
    kg: 'kg',
    completed: 'Completed',
    inProgress: 'In Progress',
    scheduled: 'Scheduled',
    noWorkoutsToday: 'No workouts scheduled for today',
    noRecentWorkouts: 'No recent workouts',
    
    // Calories Screen
    calorieTracker: 'Calorie Tracker',
    trackYourNutrition: 'Track your nutrition and meals',
    dailyGoal: 'Daily Goal',
    remaining: 'Remaining',
    consumed: 'Consumed',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snacks: 'Snacks',
    addMeal: 'Add Meal',
    logFood: 'Log Food',
    searchFood: 'Search food...',
    calories_lower: 'calories',
    protein: 'Protein',
    carbs: 'Carbs',
    fats: 'Fats',
    water: 'Water',
    glasses: 'glasses',
    noMealsLogged: 'No meals logged yet',
    
    // Profile Screen
    myProfile: 'My Profile',
    settings: 'Settings',
    editProfile: 'Edit Profile',
    statistics: 'Statistics',
    achievements: 'Achievements',
    totalWorkouts: 'Total Workouts',
    totalCalories: 'Total Calories',
    currentStreak: 'Current Streak',
    days: 'days',
    personalInfo: 'Personal Info',
    name: 'Name',
    email: 'Email',
    age: 'Age',
    height: 'Height',
    weight: 'Weight',
    goal: 'Goal',
    
    // Settings
    settingsTitle: 'Settings',
    account: 'Account',
    preferences: 'Preferences',
    localization: 'Localization',
    notifications: 'Notifications',
    language: 'Language',
    currency: 'Currency',
    theme: 'Theme',
    units: 'Units',
    enableNotifications: 'Enable Notifications',
    darkMode: 'Dark Mode',
    metric: 'Metric',
    imperial: 'Imperial',
    logout: 'Logout',
    deleteAccount: 'Delete Account',
    version: 'Version',
    about: 'About',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    selectLanguage: 'Select Language',
    selectCurrency: 'Select Currency',
    
    // Common
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    loading: 'Loading...',
    retry: 'Retry',
    success: 'Success',
    failed: 'Failed',
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    total: 'Total',
  },
  es: {
    // App & Auth
    appName: 'BetterU',
    tagline: 'Tu viaje de fitness comienza aquí',
    enterPassword: 'Ingrese la contraseña',
    login: 'Iniciar sesión',
    loggingIn: 'Iniciando sesión...',
    passwordRequired: 'Contraseña requerida',
    pleaseEnterPassword: 'Por favor ingrese su contraseña',
    incorrectPassword: 'Contraseña incorrecta',
    incorrectPasswordMessage: 'La contraseña que ingresó es incorrecta. Por favor, inténtelo de nuevo.',
    error: 'Error',
    authError: 'Error al guardar el estado de autenticación',
    
    // Tab Navigation
    calories: 'Calorías',
    workouts: 'Entrenamientos',
    plans: 'Planes',
    profile: 'Perfil',
    
    // Plans Screen
    trainingPlans: 'Planes de Entrenamiento',
    findPerfectProgram: 'Encuentra tu programa de entrenamiento perfecto',
    browsePlans: 'Explorar Planes',
    myPlans: 'Mis Planes',
    searchPlans: 'Buscar planes...',
    category: 'Categoría',
    duration: 'Duración',
    difficulty: 'Dificultad',
    all: 'Todos',
    strength: 'Fuerza',
    cardio: 'Cardio',
    flexibility: 'Flexibilidad',
    beginner: 'Principiante',
    intermediate: 'Intermedio',
    advanced: 'Avanzado',
    anyDuration: 'Cualquier Duración',
    oneToFourWeeks: '1-4 semanas',
    fiveToEightWeeks: '5-8 semanas',
    ninePlusWeeks: '9+ semanas',
    allLevels: 'Todos los Niveles',
    weeks: 'semanas',
    workoutsCount: 'entrenamientos',
    viewPlan: 'Ver Plan',
    purchase: 'Comprar',
    purchaseRequired: 'Compra Requerida',
    thisPlanCosts: 'Este plan cuesta',
    wouldYouLikeToPurchase: '¿Te gustaría comprarlo?',
    cancel: 'Cancelar',
    viewPlanDetails: 'Ver detalles del plan y entrenamientos.',
    close: 'Cerrar',
    downloadPDF: 'Descargar PDF',
    downloadPDFMessage: '¡La descarga de PDF estará disponible pronto!',
    paymentIntegration: '¡La integración de pagos se agregará pronto!',
    noPlansMatch: 'Ningún plan coincide con tus filtros',
    noPurchasedPlans: 'Aún no has comprado ningún plan',
    
    // Workouts Screen
    myWorkouts: 'Mis Entrenamientos',
    trackYourProgress: 'Rastrea tu progreso y ejercicios',
    todaysWorkout: 'Entrenamiento de Hoy',
    recentWorkouts: 'Entrenamientos Recientes',
    exerciseLibrary: 'Biblioteca de Ejercicios',
    startWorkout: 'Iniciar Entrenamiento',
    logWorkout: 'Registrar Entrenamiento',
    searchExercises: 'Buscar ejercicios...',
    sets: 'series',
    reps: 'repeticiones',
    kg: 'kg',
    completed: 'Completado',
    inProgress: 'En Progreso',
    scheduled: 'Programado',
    noWorkoutsToday: 'No hay entrenamientos programados para hoy',
    noRecentWorkouts: 'No hay entrenamientos recientes',
    
    // Calories Screen
    calorieTracker: 'Contador de Calorías',
    trackYourNutrition: 'Rastrea tu nutrición y comidas',
    dailyGoal: 'Meta Diaria',
    remaining: 'Restante',
    consumed: 'Consumido',
    breakfast: 'Desayuno',
    lunch: 'Almuerzo',
    dinner: 'Cena',
    snacks: 'Meriendas',
    addMeal: 'Agregar Comida',
    logFood: 'Registrar Alimento',
    searchFood: 'Buscar alimento...',
    calories_lower: 'calorías',
    protein: 'Proteína',
    carbs: 'Carbohidratos',
    fats: 'Grasas',
    water: 'Agua',
    glasses: 'vasos',
    noMealsLogged: 'No se han registrado comidas aún',
    
    // Profile Screen
    myProfile: 'Mi Perfil',
    settings: 'Configuración',
    editProfile: 'Editar Perfil',
    statistics: 'Estadísticas',
    achievements: 'Logros',
    totalWorkouts: 'Entrenamientos Totales',
    totalCalories: 'Calorías Totales',
    currentStreak: 'Racha Actual',
    days: 'días',
    personalInfo: 'Información Personal',
    name: 'Nombre',
    email: 'Correo',
    age: 'Edad',
    height: 'Altura',
    weight: 'Peso',
    goal: 'Objetivo',
    
    // Settings
    settingsTitle: 'Configuración',
    account: 'Cuenta',
    preferences: 'Preferencias',
    localization: 'Localización',
    notifications: 'Notificaciones',
    language: 'Idioma',
    currency: 'Moneda',
    theme: 'Tema',
    units: 'Unidades',
    enableNotifications: 'Habilitar Notificaciones',
    darkMode: 'Modo Oscuro',
    metric: 'Métrico',
    imperial: 'Imperial',
    logout: 'Cerrar Sesión',
    deleteAccount: 'Eliminar Cuenta',
    version: 'Versión',
    about: 'Acerca de',
    privacyPolicy: 'Política de Privacidad',
    termsOfService: 'Términos de Servicio',
    selectLanguage: 'Seleccionar Idioma',
    selectCurrency: 'Seleccionar Moneda',
    
    // Common
    save: 'Guardar',
    edit: 'Editar',
    delete: 'Eliminar',
    confirm: 'Confirmar',
    back: 'Atrás',
    next: 'Siguiente',
    done: 'Hecho',
    loading: 'Cargando...',
    retry: 'Reintentar',
    success: 'Éxito',
    failed: 'Fallido',
    today: 'Hoy',
    yesterday: 'Ayer',
    thisWeek: 'Esta Semana',
    thisMonth: 'Este Mes',
    total: 'Total',
  },
  fr: {
    // App & Auth
    appName: 'BetterU',
    tagline: 'Votre parcours fitness commence ici',
    enterPassword: 'Entrez le mot de passe',
    login: 'Connexion',
    loggingIn: 'Connexion en cours...',
    passwordRequired: 'Mot de passe requis',
    pleaseEnterPassword: 'Veuillez entrer votre mot de passe',
    incorrectPassword: 'Mot de passe incorrect',
    incorrectPasswordMessage: 'Le mot de passe que vous avez entré est incorrect. Veuillez réessayer.',
    error: 'Erreur',
    authError: "Échec de l'enregistrement de l'état d'authentification",
    
    // Tab Navigation
    calories: 'Calories',
    workouts: 'Entraînements',
    plans: 'Plans',
    profile: 'Profil',
    
    // Plans Screen
    trainingPlans: "Plans d'Entraînement",
    findPerfectProgram: 'Trouvez votre programme parfait',
    browsePlans: 'Parcourir les Plans',
    myPlans: 'Mes Plans',
    searchPlans: 'Rechercher des plans...',
    category: 'Catégorie',
    duration: 'Durée',
    difficulty: 'Difficulté',
    all: 'Tous',
    strength: 'Force',
    cardio: 'Cardio',
    flexibility: 'Flexibilité',
    beginner: 'Débutant',
    intermediate: 'Intermédiaire',
    advanced: 'Avancé',
    anyDuration: 'Toute Durée',
    oneToFourWeeks: '1-4 semaines',
    fiveToEightWeeks: '5-8 semaines',
    ninePlusWeeks: '9+ semaines',
    allLevels: 'Tous Niveaux',
    weeks: 'semaines',
    workoutsCount: 'entraînements',
    viewPlan: 'Voir le Plan',
    purchase: 'Acheter',
    purchaseRequired: 'Achat Requis',
    thisPlanCosts: 'Ce plan coûte',
    wouldYouLikeToPurchase: 'Voulez-vous l\'acheter?',
    cancel: 'Annuler',
    viewPlanDetails: 'Voir les détails du plan et les entraînements.',
    close: 'Fermer',
    downloadPDF: 'Télécharger PDF',
    downloadPDFMessage: 'Le téléchargement PDF sera bientôt disponible!',
    paymentIntegration: 'L\'intégration de paiement sera ajoutée bientôt!',
    noPlansMatch: 'Aucun plan ne correspond à vos filtres',
    noPurchasedPlans: "Vous n'avez encore acheté aucun plan",
    
    // Workouts Screen
    myWorkouts: 'Mes Entraînements',
    trackYourProgress: 'Suivez vos progrès et exercices',
    todaysWorkout: "Entraînement d'Aujourd'hui",
    recentWorkouts: 'Entraînements Récents',
    exerciseLibrary: "Bibliothèque d'Exercices",
    startWorkout: 'Commencer l\'Entraînement',
    logWorkout: 'Enregistrer l\'Entraînement',
    searchExercises: 'Rechercher des exercices...',
    sets: 'séries',
    reps: 'répétitions',
    kg: 'kg',
    completed: 'Terminé',
    inProgress: 'En Cours',
    scheduled: 'Programmé',
    noWorkoutsToday: "Aucun entraînement programmé aujourd'hui",
    noRecentWorkouts: 'Aucun entraînement récent',
    
    // Calories Screen
    calorieTracker: 'Compteur de Calories',
    trackYourNutrition: 'Suivez votre nutrition et repas',
    dailyGoal: 'Objectif Quotidien',
    remaining: 'Restant',
    consumed: 'Consommé',
    breakfast: 'Petit-déjeuner',
    lunch: 'Déjeuner',
    dinner: 'Dîner',
    snacks: 'Collations',
    addMeal: 'Ajouter un Repas',
    logFood: 'Enregistrer un Aliment',
    searchFood: 'Rechercher un aliment...',
    calories_lower: 'calories',
    protein: 'Protéines',
    carbs: 'Glucides',
    fats: 'Lipides',
    water: 'Eau',
    glasses: 'verres',
    noMealsLogged: 'Aucun repas enregistré',
    
    // Profile Screen
    myProfile: 'Mon Profil',
    settings: 'Paramètres',
    editProfile: 'Modifier le Profil',
    statistics: 'Statistiques',
    achievements: 'Réalisations',
    totalWorkouts: 'Entraînements Totaux',
    totalCalories: 'Calories Totales',
    currentStreak: 'Série Actuelle',
    days: 'jours',
    personalInfo: 'Informations Personnelles',
    name: 'Nom',
    email: 'Email',
    age: 'Âge',
    height: 'Taille',
    weight: 'Poids',
    goal: 'Objectif',
    
    // Settings
    settingsTitle: 'Paramètres',
    account: 'Compte',
    preferences: 'Préférences',
    localization: 'Localisation',
    notifications: 'Notifications',
    language: 'Langue',
    currency: 'Devise',
    theme: 'Thème',
    units: 'Unités',
    enableNotifications: 'Activer les Notifications',
    darkMode: 'Mode Sombre',
    metric: 'Métrique',
    imperial: 'Impérial',
    logout: 'Déconnexion',
    deleteAccount: 'Supprimer le Compte',
    version: 'Version',
    about: 'À Propos',
    privacyPolicy: 'Politique de Confidentialité',
    termsOfService: 'Conditions d\'Utilisation',
    selectLanguage: 'Sélectionner la Langue',
    selectCurrency: 'Sélectionner la Devise',
    
    // Common
    save: 'Enregistrer',
    edit: 'Modifier',
    delete: 'Supprimer',
    confirm: 'Confirmer',
    back: 'Retour',
    next: 'Suivant',
    done: 'Terminé',
    loading: 'Chargement...',
    retry: 'Réessayer',
    success: 'Succès',
    failed: 'Échoué',
    today: "Aujourd'hui",
    yesterday: 'Hier',
    thisWeek: 'Cette Semaine',
    thisMonth: 'Ce Mois',
    total: 'Total',
  },
  de: {
    // App & Auth
    appName: 'BetterU',
    tagline: 'Ihre Fitnessreise beginnt hier',
    enterPassword: 'Passwort eingeben',
    login: 'Anmelden',
    loggingIn: 'Anmeldung läuft...',
    passwordRequired: 'Passwort erforderlich',
    pleaseEnterPassword: 'Bitte geben Sie Ihr Passwort ein',
    incorrectPassword: 'Falsches Passwort',
    incorrectPasswordMessage: 'Das eingegebene Passwort ist falsch. Bitte versuchen Sie es erneut.',
    error: 'Fehler',
    authError: 'Fehler beim Speichern des Authentifizierungsstatus',
    
    // Tab Navigation
    calories: 'Kalorien',
    workouts: 'Workouts',
    plans: 'Pläne',
    profile: 'Profil',
    
    // Plans Screen
    trainingPlans: 'Trainingspläne',
    findPerfectProgram: 'Finden Sie Ihr perfektes Trainingsprogramm',
    browsePlans: 'Pläne Durchsuchen',
    myPlans: 'Meine Pläne',
    searchPlans: 'Pläne suchen...',
    category: 'Kategorie',
    duration: 'Dauer',
    difficulty: 'Schwierigkeit',
    all: 'Alle',
    strength: 'Kraft',
    cardio: 'Cardio',
    flexibility: 'Flexibilität',
    beginner: 'Anfänger',
    intermediate: 'Fortgeschritten',
    advanced: 'Experte',
    anyDuration: 'Beliebige Dauer',
    oneToFourWeeks: '1-4 Wochen',
    fiveToEightWeeks: '5-8 Wochen',
    ninePlusWeeks: '9+ Wochen',
    allLevels: 'Alle Stufen',
    weeks: 'Wochen',
    workoutsCount: 'Workouts',
    viewPlan: 'Plan Ansehen',
    purchase: 'Kaufen',
    purchaseRequired: 'Kauf Erforderlich',
    thisPlanCosts: 'Dieser Plan kostet',
    wouldYouLikeToPurchase: 'Möchten Sie ihn kaufen?',
    cancel: 'Abbrechen',
    viewPlanDetails: 'Plandetails und Workouts ansehen.',
    close: 'Schließen',
    downloadPDF: 'PDF Herunterladen',
    downloadPDFMessage: 'PDF-Download wird bald verfügbar sein!',
    paymentIntegration: 'Zahlungsintegration wird bald hinzugefügt!',
    noPlansMatch: 'Keine Pläne entsprechen Ihren Filtern',
    noPurchasedPlans: 'Sie haben noch keine Pläne gekauft',
    
    // Workouts Screen
    myWorkouts: 'Meine Workouts',
    trackYourProgress: 'Verfolgen Sie Ihren Fortschritt und Übungen',
    todaysWorkout: 'Heutiges Workout',
    recentWorkouts: 'Letzte Workouts',
    exerciseLibrary: 'Übungsbibliothek',
    startWorkout: 'Workout Starten',
    logWorkout: 'Workout Protokollieren',
    searchExercises: 'Übungen suchen...',
    sets: 'Sätze',
    reps: 'Wiederholungen',
    kg: 'kg',
    completed: 'Abgeschlossen',
    inProgress: 'In Bearbeitung',
    scheduled: 'Geplant',
    noWorkoutsToday: 'Keine Workouts für heute geplant',
    noRecentWorkouts: 'Keine letzten Workouts',
    
    // Calories Screen
    calorieTracker: 'Kalorienzähler',
    trackYourNutrition: 'Verfolgen Sie Ihre Ernährung und Mahlzeiten',
    dailyGoal: 'Tagesziel',
    remaining: 'Verbleibend',
    consumed: 'Verbraucht',
    breakfast: 'Frühstück',
    lunch: 'Mittagessen',
    dinner: 'Abendessen',
    snacks: 'Snacks',
    addMeal: 'Mahlzeit Hinzufügen',
    logFood: 'Lebensmittel Protokollieren',
    searchFood: 'Lebensmittel suchen...',
    calories_lower: 'Kalorien',
    protein: 'Protein',
    carbs: 'Kohlenhydrate',
    fats: 'Fette',
    water: 'Wasser',
    glasses: 'Gläser',
    noMealsLogged: 'Noch keine Mahlzeiten protokolliert',
    
    // Profile Screen
    myProfile: 'Mein Profil',
    settings: 'Einstellungen',
    editProfile: 'Profil Bearbeiten',
    statistics: 'Statistiken',
    achievements: 'Erfolge',
    totalWorkouts: 'Gesamt Workouts',
    totalCalories: 'Gesamt Kalorien',
    currentStreak: 'Aktuelle Serie',
    days: 'Tage',
    personalInfo: 'Persönliche Informationen',
    name: 'Name',
    email: 'E-Mail',
    age: 'Alter',
    height: 'Größe',
    weight: 'Gewicht',
    goal: 'Ziel',
    
    // Settings
    settingsTitle: 'Einstellungen',
    account: 'Konto',
    preferences: 'Präferenzen',
    localization: 'Lokalisierung',
    notifications: 'Benachrichtigungen',
    language: 'Sprache',
    currency: 'Währung',
    theme: 'Design',
    units: 'Einheiten',
    enableNotifications: 'Benachrichtigungen Aktivieren',
    darkMode: 'Dunkler Modus',
    metric: 'Metrisch',
    imperial: 'Imperial',
    logout: 'Abmelden',
    deleteAccount: 'Konto Löschen',
    version: 'Version',
    about: 'Über',
    privacyPolicy: 'Datenschutzrichtlinie',
    termsOfService: 'Nutzungsbedingungen',
    selectLanguage: 'Sprache Auswählen',
    selectCurrency: 'Währung Auswählen',
    
    // Common
    save: 'Speichern',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    confirm: 'Bestätigen',
    back: 'Zurück',
    next: 'Weiter',
    done: 'Fertig',
    loading: 'Lädt...',
    retry: 'Wiederholen',
    success: 'Erfolg',
    failed: 'Fehlgeschlagen',
    today: 'Heute',
    yesterday: 'Gestern',
    thisWeek: 'Diese Woche',
    thisMonth: 'Dieser Monat',
    total: 'Gesamt',
  },
  pt: {
    // App & Auth
    appName: 'BetterU',
    tagline: 'Sua jornada fitness começa aqui',
    enterPassword: 'Digite a senha',
    login: 'Entrar',
    loggingIn: 'Entrando...',
    passwordRequired: 'Senha necessária',
    pleaseEnterPassword: 'Por favor, digite sua senha',
    incorrectPassword: 'Senha incorreta',
    incorrectPasswordMessage: 'A senha que você digitou está incorreta. Por favor, tente novamente.',
    error: 'Erro',
    authError: 'Falha ao salvar o estado de autenticação',
    
    // Tab Navigation
    calories: 'Calorias',
    workouts: 'Treinos',
    plans: 'Planos',
    profile: 'Perfil',
    
    // Plans Screen
    trainingPlans: 'Planos de Treino',
    findPerfectProgram: 'Encontre seu programa perfeito',
    browsePlans: 'Explorar Planos',
    myPlans: 'Meus Planos',
    searchPlans: 'Buscar planos...',
    category: 'Categoria',
    duration: 'Duração',
    difficulty: 'Dificuldade',
    all: 'Todos',
    strength: 'Força',
    cardio: 'Cardio',
    flexibility: 'Flexibilidade',
    beginner: 'Iniciante',
    intermediate: 'Intermediário',
    advanced: 'Avançado',
    anyDuration: 'Qualquer Duração',
    oneToFourWeeks: '1-4 semanas',
    fiveToEightWeeks: '5-8 semanas',
    ninePlusWeeks: '9+ semanas',
    allLevels: 'Todos os Níveis',
    weeks: 'semanas',
    workoutsCount: 'treinos',
    viewPlan: 'Ver Plano',
    purchase: 'Comprar',
    purchaseRequired: 'Compra Necessária',
    thisPlanCosts: 'Este plano custa',
    wouldYouLikeToPurchase: 'Gostaria de comprá-lo?',
    cancel: 'Cancelar',
    viewPlanDetails: 'Ver detalhes do plano e treinos.',
    close: 'Fechar',
    downloadPDF: 'Baixar PDF',
    downloadPDFMessage: 'O download do PDF estará disponível em breve!',
    paymentIntegration: 'A integração de pagamento será adicionada em breve!',
    noPlansMatch: 'Nenhum plano corresponde aos seus filtros',
    noPurchasedPlans: 'Você ainda não comprou nenhum plano',
    
    // Workouts Screen
    myWorkouts: 'Meus Treinos',
    trackYourProgress: 'Acompanhe seu progresso e exercícios',
    todaysWorkout: 'Treino de Hoje',
    recentWorkouts: 'Treinos Recentes',
    exerciseLibrary: 'Biblioteca de Exercícios',
    startWorkout: 'Iniciar Treino',
    logWorkout: 'Registrar Treino',
    searchExercises: 'Buscar exercícios...',
    sets: 'séries',
    reps: 'repetições',
    kg: 'kg',
    completed: 'Concluído',
    inProgress: 'Em Andamento',
    scheduled: 'Agendado',
    noWorkoutsToday: 'Nenhum treino agendado para hoje',
    noRecentWorkouts: 'Nenhum treino recente',
    
    // Calories Screen
    calorieTracker: 'Contador de Calorias',
    trackYourNutrition: 'Acompanhe sua nutrição e refeições',
    dailyGoal: 'Meta Diária',
    remaining: 'Restante',
    consumed: 'Consumido',
    breakfast: 'Café da Manhã',
    lunch: 'Almoço',
    dinner: 'Jantar',
    snacks: 'Lanches',
    addMeal: 'Adicionar Refeição',
    logFood: 'Registrar Alimento',
    searchFood: 'Buscar alimento...',
    calories_lower: 'calorias',
    protein: 'Proteína',
    carbs: 'Carboidratos',
    fats: 'Gorduras',
    water: 'Água',
    glasses: 'copos',
    noMealsLogged: 'Nenhuma refeição registrada ainda',
    
    // Profile Screen
    myProfile: 'Meu Perfil',
    settings: 'Configurações',
    editProfile: 'Editar Perfil',
    statistics: 'Estatísticas',
    achievements: 'Conquistas',
    totalWorkouts: 'Treinos Totais',
    totalCalories: 'Calorias Totais',
    currentStreak: 'Sequência Atual',
    days: 'dias',
    personalInfo: 'Informações Pessoais',
    name: 'Nome',
    email: 'Email',
    age: 'Idade',
    height: 'Altura',
    weight: 'Peso',
    goal: 'Objetivo',
    
    // Settings
    settingsTitle: 'Configurações',
    account: 'Conta',
    preferences: 'Preferências',
    localization: 'Localização',
    notifications: 'Notificações',
    language: 'Idioma',
    currency: 'Moeda',
    theme: 'Tema',
    units: 'Unidades',
    enableNotifications: 'Ativar Notificações',
    darkMode: 'Modo Escuro',
    metric: 'Métrico',
    imperial: 'Imperial',
    logout: 'Sair',
    deleteAccount: 'Excluir Conta',
    version: 'Versão',
    about: 'Sobre',
    privacyPolicy: 'Política de Privacidade',
    termsOfService: 'Termos de Serviço',
    selectLanguage: 'Selecionar Idioma',
    selectCurrency: 'Selecionar Moeda',
    
    // Common
    save: 'Salvar',
    edit: 'Editar',
    delete: 'Excluir',
    confirm: 'Confirmar',
    back: 'Voltar',
    next: 'Próximo',
    done: 'Concluído',
    loading: 'Carregando...',
    retry: 'Tentar Novamente',
    success: 'Sucesso',
    failed: 'Falhou',
    today: 'Hoje',
    yesterday: 'Ontem',
    thisWeek: 'Esta Semana',
    thisMonth: 'Este Mês',
    total: 'Total',
  },
  it: {
    // App & Auth
    appName: 'BetterU',
    tagline: 'Il tuo viaggio fitness inizia qui',
    enterPassword: 'Inserisci la password',
    login: 'Accedi',
    loggingIn: 'Accesso in corso...',
    passwordRequired: 'Password richiesta',
    pleaseEnterPassword: 'Inserisci la tua password',
    incorrectPassword: 'Password errata',
    incorrectPasswordMessage: 'La password inserita non è corretta. Riprova.',
    error: 'Errore',
    authError: "Impossibile salvare lo stato di autenticazione",
    
    // Tab Navigation
    calories: 'Calorie',
    workouts: 'Allenamenti',
    plans: 'Piani',
    profile: 'Profilo',
    
    // Plans Screen
    trainingPlans: 'Piani di Allenamento',
    findPerfectProgram: 'Trova il tuo programma perfetto',
    browsePlans: 'Sfoglia Piani',
    myPlans: 'I Miei Piani',
    searchPlans: 'Cerca piani...',
    category: 'Categoria',
    duration: 'Durata',
    difficulty: 'Difficoltà',
    all: 'Tutti',
    strength: 'Forza',
    cardio: 'Cardio',
    flexibility: 'Flessibilità',
    beginner: 'Principiante',
    intermediate: 'Intermedio',
    advanced: 'Avanzato',
    anyDuration: 'Qualsiasi Durata',
    oneToFourWeeks: '1-4 settimane',
    fiveToEightWeeks: '5-8 settimane',
    ninePlusWeeks: '9+ settimane',
    allLevels: 'Tutti i Livelli',
    weeks: 'settimane',
    workoutsCount: 'allenamenti',
    viewPlan: 'Visualizza Piano',
    purchase: 'Acquista',
    purchaseRequired: 'Acquisto Richiesto',
    thisPlanCosts: 'Questo piano costa',
    wouldYouLikeToPurchase: 'Vuoi acquistarlo?',
    cancel: 'Annulla',
    viewPlanDetails: 'Visualizza dettagli del piano e allenamenti.',
    close: 'Chiudi',
    downloadPDF: 'Scarica PDF',
    downloadPDFMessage: 'Il download PDF sarà disponibile presto!',
    paymentIntegration: 'L\'integrazione dei pagamenti sarà aggiunta presto!',
    noPlansMatch: 'Nessun piano corrisponde ai tuoi filtri',
    noPurchasedPlans: 'Non hai ancora acquistato nessun piano',
    
    // Workouts Screen
    myWorkouts: 'I Miei Allenamenti',
    trackYourProgress: 'Traccia i tuoi progressi ed esercizi',
    todaysWorkout: 'Allenamento di Oggi',
    recentWorkouts: 'Allenamenti Recenti',
    exerciseLibrary: 'Biblioteca Esercizi',
    startWorkout: 'Inizia Allenamento',
    logWorkout: 'Registra Allenamento',
    searchExercises: 'Cerca esercizi...',
    sets: 'serie',
    reps: 'ripetizioni',
    kg: 'kg',
    completed: 'Completato',
    inProgress: 'In Corso',
    scheduled: 'Programmato',
    noWorkoutsToday: 'Nessun allenamento programmato per oggi',
    noRecentWorkouts: 'Nessun allenamento recente',
    
    // Calories Screen
    calorieTracker: 'Contatore Calorie',
    trackYourNutrition: 'Traccia la tua nutrizione e pasti',
    dailyGoal: 'Obiettivo Giornaliero',
    remaining: 'Rimanente',
    consumed: 'Consumato',
    breakfast: 'Colazione',
    lunch: 'Pranzo',
    dinner: 'Cena',
    snacks: 'Spuntini',
    addMeal: 'Aggiungi Pasto',
    logFood: 'Registra Cibo',
    searchFood: 'Cerca cibo...',
    calories_lower: 'calorie',
    protein: 'Proteine',
    carbs: 'Carboidrati',
    fats: 'Grassi',
    water: 'Acqua',
    glasses: 'bicchieri',
    noMealsLogged: 'Nessun pasto registrato ancora',
    
    // Profile Screen
    myProfile: 'Il Mio Profilo',
    settings: 'Impostazioni',
    editProfile: 'Modifica Profilo',
    statistics: 'Statistiche',
    achievements: 'Risultati',
    totalWorkouts: 'Allenamenti Totali',
    totalCalories: 'Calorie Totali',
    currentStreak: 'Serie Attuale',
    days: 'giorni',
    personalInfo: 'Informazioni Personali',
    name: 'Nome',
    email: 'Email',
    age: 'Età',
    height: 'Altezza',
    weight: 'Peso',
    goal: 'Obiettivo',
    
    // Settings
    settingsTitle: 'Impostazioni',
    account: 'Account',
    preferences: 'Preferenze',
    localization: 'Localizzazione',
    notifications: 'Notifiche',
    language: 'Lingua',
    currency: 'Valuta',
    theme: 'Tema',
    units: 'Unità',
    enableNotifications: 'Abilita Notifiche',
    darkMode: 'Modalità Scura',
    metric: 'Metrico',
    imperial: 'Imperiale',
    logout: 'Esci',
    deleteAccount: 'Elimina Account',
    version: 'Versione',
    about: 'Informazioni',
    privacyPolicy: 'Informativa sulla Privacy',
    termsOfService: 'Termini di Servizio',
    selectLanguage: 'Seleziona Lingua',
    selectCurrency: 'Seleziona Valuta',
    
    // Common
    save: 'Salva',
    edit: 'Modifica',
    delete: 'Elimina',
    confirm: 'Conferma',
    back: 'Indietro',
    next: 'Avanti',
    done: 'Fatto',
    loading: 'Caricamento...',
    retry: 'Riprova',
    success: 'Successo',
    failed: 'Fallito',
    today: 'Oggi',
    yesterday: 'Ieri',
    thisWeek: 'Questa Settimana',
    thisMonth: 'Questo Mese',
    total: 'Totale',
  },
  ja: {
    // App & Auth
    appName: 'BetterU',
    tagline: 'あなたのフィットネスの旅はここから始まります',
    enterPassword: 'パスワードを入力',
    login: 'ログイン',
    loggingIn: 'ログイン中...',
    passwordRequired: 'パスワードが必要です',
    pleaseEnterPassword: 'パスワードを入力してください',
    incorrectPassword: 'パスワードが正しくありません',
    incorrectPasswordMessage: '入力されたパスワードが正しくありません。もう一度お試しください。',
    error: 'エラー',
    authError: '認証状態の保存に失敗しました',
    
    // Tab Navigation
    calories: 'カロリー',
    workouts: 'ワークアウト',
    plans: 'プラン',
    profile: 'プロフィール',
    
    // Plans Screen
    trainingPlans: 'トレーニングプラン',
    findPerfectProgram: '完璧なプログラムを見つけよう',
    browsePlans: 'プランを閲覧',
    myPlans: 'マイプラン',
    searchPlans: 'プランを検索...',
    category: 'カテゴリー',
    duration: '期間',
    difficulty: '難易度',
    all: 'すべて',
    strength: '筋力',
    cardio: '有酸素運動',
    flexibility: '柔軟性',
    beginner: '初心者',
    intermediate: '中級者',
    advanced: '上級者',
    anyDuration: '任意の期間',
    oneToFourWeeks: '1-4週間',
    fiveToEightWeeks: '5-8週間',
    ninePlusWeeks: '9週間以上',
    allLevels: 'すべてのレベル',
    weeks: '週間',
    workoutsCount: 'ワークアウト',
    viewPlan: 'プランを表示',
    purchase: '購入',
    purchaseRequired: '購入が必要です',
    thisPlanCosts: 'このプランの価格は',
    wouldYouLikeToPurchase: '購入しますか？',
    cancel: 'キャンセル',
    viewPlanDetails: 'プランの詳細とワークアウトを表示します。',
    close: '閉じる',
    downloadPDF: 'PDFをダウンロード',
    downloadPDFMessage: 'PDFダウンロードは近日公開予定です！',
    paymentIntegration: '支払い統合は近日追加予定です！',
    noPlansMatch: 'フィルターに一致するプランがありません',
    noPurchasedPlans: 'まだプランを購入していません',
    
    // Workouts Screen
    myWorkouts: 'マイワークアウト',
    trackYourProgress: '進捗とエクササイズを追跡',
    todaysWorkout: '今日のワークアウト',
    recentWorkouts: '最近のワークアウト',
    exerciseLibrary: 'エクササイズライブラリ',
    startWorkout: 'ワークアウトを開始',
    logWorkout: 'ワークアウトを記録',
    searchExercises: 'エクササイズを検索...',
    sets: 'セット',
    reps: '回',
    kg: 'kg',
    completed: '完了',
    inProgress: '進行中',
    scheduled: '予定',
    noWorkoutsToday: '今日のワークアウトはありません',
    noRecentWorkouts: '最近のワークアウトはありません',
    
    // Calories Screen
    calorieTracker: 'カロリートラッカー',
    trackYourNutrition: '栄養と食事を追跡',
    dailyGoal: '1日の目標',
    remaining: '残り',
    consumed: '摂取済み',
    breakfast: '朝食',
    lunch: '昼食',
    dinner: '夕食',
    snacks: 'スナック',
    addMeal: '食事を追加',
    logFood: '食品を記録',
    searchFood: '食品を検索...',
    calories_lower: 'カロリー',
    protein: 'タンパク質',
    carbs: '炭水化物',
    fats: '脂質',
    water: '水',
    glasses: 'グラス',
    noMealsLogged: 'まだ食事が記録されていません',
    
    // Profile Screen
    myProfile: 'マイプロフィール',
    settings: '設定',
    editProfile: 'プロフィールを編集',
    statistics: '統計',
    achievements: '実績',
    totalWorkouts: '総ワークアウト数',
    totalCalories: '総カロリー',
    currentStreak: '現在の連続記録',
    days: '日',
    personalInfo: '個人情報',
    name: '名前',
    email: 'メール',
    age: '年齢',
    height: '身長',
    weight: '体重',
    goal: '目標',
    
    // Settings
    settingsTitle: '設定',
    account: 'アカウント',
    preferences: '環境設定',
    localization: 'ローカライゼーション',
    notifications: '通知',
    language: '言語',
    currency: '通貨',
    theme: 'テーマ',
    units: '単位',
    enableNotifications: '通知を有効にする',
    darkMode: 'ダークモード',
    metric: 'メートル法',
    imperial: 'ヤード・ポンド法',
    logout: 'ログアウト',
    deleteAccount: 'アカウントを削除',
    version: 'バージョン',
    about: '概要',
    privacyPolicy: 'プライバシーポリシー',
    termsOfService: '利用規約',
    selectLanguage: '言語を選択',
    selectCurrency: '通貨を選択',
    
    // Common
    save: '保存',
    edit: '編集',
    delete: '削除',
    confirm: '確認',
    back: '戻る',
    next: '次へ',
    done: '完了',
    loading: '読み込み中...',
    retry: '再試行',
    success: '成功',
    failed: '失敗',
    today: '今日',
    yesterday: '昨日',
    thisWeek: '今週',
    thisMonth: '今月',
    total: '合計',
  },
  zh: {
    // App & Auth
    appName: 'BetterU',
    tagline: '您的健身之旅从这里开始',
    enterPassword: '输入密码',
    login: '登录',
    loggingIn: '登录中...',
    passwordRequired: '需要密码',
    pleaseEnterPassword: '请输入您的密码',
    incorrectPassword: '密码错误',
    incorrectPasswordMessage: '您输入的密码不正确。请重试。',
    error: '错误',
    authError: '保存认证状态失败',
    
    // Tab Navigation
    calories: '卡路里',
    workouts: '锻炼',
    plans: '计划',
    profile: '个人资料',
    
    // Plans Screen
    trainingPlans: '训练计划',
    findPerfectProgram: '找到您的完美计划',
    browsePlans: '浏览计划',
    myPlans: '我的计划',
    searchPlans: '搜索计划...',
    category: '类别',
    duration: '持续时间',
    difficulty: '难度',
    all: '全部',
    strength: '力量',
    cardio: '有氧',
    flexibility: '柔韧性',
    beginner: '初学者',
    intermediate: '中级',
    advanced: '高级',
    anyDuration: '任意时长',
    oneToFourWeeks: '1-4周',
    fiveToEightWeeks: '5-8周',
    ninePlusWeeks: '9周以上',
    allLevels: '所有级别',
    weeks: '周',
    workoutsCount: '锻炼',
    viewPlan: '查看计划',
    purchase: '购买',
    purchaseRequired: '需要购买',
    thisPlanCosts: '此计划费用为',
    wouldYouLikeToPurchase: '您想购买吗？',
    cancel: '取消',
    viewPlanDetails: '查看计划详情和锻炼。',
    close: '关闭',
    downloadPDF: '下载PDF',
    downloadPDFMessage: 'PDF下载即将推出！',
    paymentIntegration: '支付集成即将添加！',
    noPlansMatch: '没有符合您筛选条件的计划',
    noPurchasedPlans: '您还没有购买任何计划',
    
    // Workouts Screen
    myWorkouts: '我的锻炼',
    trackYourProgress: '跟踪您的进度和练习',
    todaysWorkout: '今日锻炼',
    recentWorkouts: '最近的锻炼',
    exerciseLibrary: '练习库',
    startWorkout: '开始锻炼',
    logWorkout: '记录锻炼',
    searchExercises: '搜索练习...',
    sets: '组',
    reps: '次',
    kg: '公斤',
    completed: '已完成',
    inProgress: '进行中',
    scheduled: '已安排',
    noWorkoutsToday: '今天没有安排锻炼',
    noRecentWorkouts: '没有最近的锻炼',
    
    // Calories Screen
    calorieTracker: '卡路里追踪器',
    trackYourNutrition: '跟踪您的营养和膳食',
    dailyGoal: '每日目标',
    remaining: '剩余',
    consumed: '已消耗',
    breakfast: '早餐',
    lunch: '午餐',
    dinner: '晚餐',
    snacks: '零食',
    addMeal: '添加餐食',
    logFood: '记录食物',
    searchFood: '搜索食物...',
    calories_lower: '卡路里',
    protein: '蛋白质',
    carbs: '碳水化合物',
    fats: '脂肪',
    water: '水',
    glasses: '杯',
    noMealsLogged: '还没有记录餐食',
    
    // Profile Screen
    myProfile: '我的资料',
    settings: '设置',
    editProfile: '编辑资料',
    statistics: '统计',
    achievements: '成就',
    totalWorkouts: '总锻炼次数',
    totalCalories: '总卡路里',
    currentStreak: '当前连续记录',
    days: '天',
    personalInfo: '个人信息',
    name: '姓名',
    email: '邮箱',
    age: '年龄',
    height: '身高',
    weight: '体重',
    goal: '目标',
    
    // Settings
    settingsTitle: '设置',
    account: '账户',
    preferences: '偏好设置',
    localization: '本地化',
    notifications: '通知',
    language: '语言',
    currency: '货币',
    theme: '主题',
    units: '单位',
    enableNotifications: '启用通知',
    darkMode: '深色模式',
    metric: '公制',
    imperial: '英制',
    logout: '登出',
    deleteAccount: '删除账户',
    version: '版本',
    about: '关于',
    privacyPolicy: '隐私政策',
    termsOfService: '服务条款',
    selectLanguage: '选择语言',
    selectCurrency: '选择货币',
    
    // Common
    save: '保存',
    edit: '编辑',
    delete: '删除',
    confirm: '确认',
    back: '返回',
    next: '下一步',
    done: '完成',
    loading: '加载中...',
    retry: '重试',
    success: '成功',
    failed: '失败',
    today: '今天',
    yesterday: '昨天',
    thisWeek: '本周',
    thisMonth: '本月',
    total: '总计',
  },
};

// Currency symbols based on locale
export const currencySymbols: { [key: string]: string } = {
  USD: '$',
  EUR: '€',
  GBP: '£',
  JPY: '¥',
  CNY: '¥',
  INR: '₹',
  AUD: 'A$',
  CAD: 'C$',
  CHF: 'CHF',
  BRL: 'R$',
  MXN: 'MX$',
  ZAR: 'R',
  KRW: '₩',
  RUB: '₽',
  SEK: 'kr',
  NOK: 'kr',
  DKK: 'kr',
  PLN: 'zł',
  TRY: '₺',
  AED: 'د.إ',
  SAR: '﷼',
};

// Get language based on device locale
export function getDeviceLanguage(): keyof typeof translations {
  const locales = Localization.getLocales();
  const primaryLocale = locales[0];
  
  if (!primaryLocale) return 'en';
  
  const languageCode = primaryLocale.languageCode;
  
  // Map language codes to supported languages
  if (languageCode === 'es') return 'es';
  if (languageCode === 'fr') return 'fr';
  if (languageCode === 'de') return 'de';
  if (languageCode === 'pt') return 'pt';
  if (languageCode === 'it') return 'it';
  if (languageCode === 'ja') return 'ja';
  if (languageCode === 'zh') return 'zh';
  
  return 'en'; // Default to English
}

// Get currency based on device locale
export function getDeviceCurrency(): string {
  const locales = Localization.getLocales();
  const primaryLocale = locales[0];
  
  if (!primaryLocale || !primaryLocale.currencyCode) {
    return 'USD'; // Default to USD
  }
  
  return primaryLocale.currencyCode;
}

// Get currency symbol
export function getCurrencySymbol(currencyCode?: string): string {
  const currency = currencyCode || getDeviceCurrency();
  return currencySymbols[currency] || currency;
}

// Translation function
export function t(key: string, language: keyof typeof translations = 'en'): string {
  return translations[language][key as keyof typeof translations['en']] || key;
}

// Format currency with proper symbol and positioning
export function formatCurrency(amount: number, currencyCode?: string): string {
  const currency = currencyCode || getDeviceCurrency();
  const symbol = getCurrencySymbol(currency);
  const formattedAmount = amount.toFixed(2);
  
  // Currencies that go after the amount
  const symbolAfter = ['EUR', 'SEK', 'NOK', 'DKK', 'PLN'];
  
  if (symbolAfter.includes(currency)) {
    return `${formattedAmount}${symbol}`;
  }
  
  return `${symbol}${formattedAmount}`;
}
